### PR TITLE
Update memmap2 version

### PR DESCRIPTION
**Pull request by syrusakbary**

### CODE REVIEW

**Comment by CensoredUsername** [comment]
👍

**Comment by syrusakbary** [comment]
Can we merge and release a new version @CensoredUsername?

Thanks!

**Comment by CensoredUsername** [comment]
Suffering a bit of a cold right now, I'll get to it once the opportunity arises.

**Comment by syrusakbary** [comment]
Feel better!

**Comment by CensoredUsername** [comment]
It's released!

**Comment by syrusakbary** [comment]
Nice! Thanks

**Pull request merged**
